export default {
  structureType: "Popup",
  name: "applicationFloatFilterPopup",
  props: {
    header: "Фильтр",
    submitBtns: true,
    submitEvent: "filteringApplicationFloatList",
    width: 800,
    activePoup: false,
    submitLabel: "Применить",
    canselLabel: "Отмена",
    cancelLabel: "Отмена",
    filter: true
  },
  components: [
    {
      id: 1,
      parentId: 0,
      componentName: "shipName",
      component: "EPCSFormInput",
      props: {
        label: "Судно",
        labelPosition: "left",
        type: "select",
        placeholder: "Судно",
        // searchEnabled: true,
        // searchEnabledMode: "startswith",
        // showClearButton: true,
        // minSearchLength: 1,
      },
    },
    {
      id: 2,
      parentId: 0,
      componentName: "outgoingNumber",
      component: "EPCSFormInput",
      props: {
        label: "Входящий номер",
        labelPosition: "left",
        type: "select",
        placeholder: "Входящий номер",
        // searchEnabled: true,
        // searchEnabledMode: "startswith",
        // showClearButton: true,
        // minSearchLength: 1,
      },
    },
    {
      id: 3,
      parentId: 0,
      componentName: "statusName",
      component: "EPCSFormInput",
      props: {
        label: "Статус",
        labelPosition: "left",
        type: "select",
        placeholder: "Статус",
      },
    },
    {
      id: 4,
      parentId: 0,
      priority: 1,
      componentName: "EPCSDirection",
      component: "EPCSDirection",
      props: {
        type: "row",
      },
    },
    {
      id: 5,
      componentName: "dateBefore",
      parentId: 4,
      col: 6,
      component: "EPCSFormInput",
      props: {
        label: "От",
        labelPosition: "left",
        value: "",
        placeholder: "дд.мм.гггг",
        format: "d.MM.yyyy",
        type: "date",
        event: "selectDateBefore",
      },
    },
    {
      id: 6,
      componentName: "dateAfter",
      parentId: 4,
      col: 6,
      component: "EPCSFormInput",
      props: {
        type: "date",
        placeholder: "дд.мм.гггг",
        direction: "row",
        format: "d.MM.yyyy",
        label: "До",
        labelPosition: "left",
        event: "selectDateAfter",
      },
    },
  ],
};
