// import structureForm from "../../structure/structureForm";
// import api from "../../api";
// import moment from "moment";
var state = {
  gmiloUrl: 'asdas',
  actualDataGrid: [
    {
      id: 1,
      nameDisp: "CreateDispAqua",
      createDate: "07.02.2021 08:00:00",
      // "createDate": "2022-02-01T10:00:00.000Z",
      shipName: "VLADIMIR VIZE",
      imo: "9750658",
    },
    {
      id: 2,
      nameDisp: "EnterDispAqua",
      createDate: "07.02.2018 08:00:00",
      shipName: "НеНадежда",
      imo: "9750658",
    },
    {
      id: 3,
      nameDisp: "SwimDispAqua",
      createDate: "07.02.2016 08:00:00",
      shipName: "НадеждаНадежд",
      imo: "12312344567",
    },
    {
      id: 4,
      nameDisp: "CreateDispAqua",
      createDate: "05.02.2022 08:00:00",
      shipName: "НадеждаМойКомпас",
      imo: "1234553467",
    },
    {
      id: 5,
      nameDisp: "ExitSeePort",
      createDate: "06.02.2021 08:00:00",
      shipName: "НадеждаИвановна",
      imo: "1238904567",
    },
    {
      id: 6,
      nameDisp: "CreateDispAqua",
      createDate: "07.02.2021 08:00:00",
      shipName: "Надежда Петровна",
      imo: "1234567",
    },
    {
      id: 7,
      nameDisp: "CreateDispAqua",
      createDate: "08.02.2021 08:00:00",
      shipName: "НадеждаНадеждНадежда",
      imo: "1234567",
    },
    {
      id: 8,
      nameDisp: "CreateDispAqua",
      createDate: "09.02.2021 08:00:00",
      shipName: "НадеждаСудов",
      imo: "1234567",
    },
    {
      id: 9,
      nameDisp: "CreateDispAqua",
      createDate: "10.02.2022 08:00:00",
      shipName: "НадеждаЙовойна",
      imo: "1234567",
    },
    {
      id: 10,
      nameDisp: "CreateDispAqua",
      createDate: "11.02.2022 07:00:00",
      shipName: "Надеждаааа",
      imo: "1234567",
    },
    {
      id: 11,
      nameDisp: "CreateDispAqua",
      createDate: "12.02.2022 08:00:00",
      shipName: "ЭннаНадежда",
      imo: "1234567",
    },
    {
      id: 12,
      nameDisp: "CreateDispAqua",
      createDate: "30.02.2022 08:00:00",
      shipName: "НадеждеНадежд",
      imo: "1234567",
    },
  ],
  settingsFilter: {},
  filledForms: {},
  allShips: [],
  backendForms: {
    EnterSeePort: ["createDate", "placeNsr", "placeNsrLon", "placeNsrLat", "placeNsrDate", "shipId"],
    EnterDispAqua: [
      "enterDate",
      "enterPlace",
      "enterLon",
      "enterLat",
      "course",
      "speed",
      "exitDate",
      "exitPlace",
      "exitLon",
      "exitLat",
      "exitType",
      "createDate",
      "shipId",
    ],
    ExitDispAqua: ["createDate", "course", "speed", "exitDate", "exitPlace", "exitLon", "exitLat", "shipId"],
    CreateDispAqua: [
      "createDate",
      "departurePlace",
      "departureLon",
      "departureLat",
      "departureDate",
      "destinationPlace",
      "destinationLon",
      "destinationLat",
      "destinationDate",
      "draught",
      "fuelLight",
      "fuelHeavy",
      "fuelSpg",
      "fuelDays",
      "waterDays",
      "provisionDays",
      "crew",
      "passangers",
      "damage",
      "enterPlace",
      "enterLon",
      "enterLat",
      "enterDate",
      "shipId",
    ],
    ExitSeePort: [
      "createDate",
      "departurePlace",
      "departureLon",
      "departureLat",
      "departureDate",
      "destinationPlace",
      "destinationLon",
      "destinationLat",
      "destinationDate",
      "draught",
      "fuelLight",
      "fuelHeavy",
      "fuelSpg",
      "fuelDays",
      "waterDays",
      "provisionDays",
      "crew",
      "passangers",
      "damage",
      "exitPlace",
      "exitLon",
      "exitLat",
      "exitDate",
      "exitType",
      "shipId",
    ],
    SwimDispAqua:[
        "createDate",
        "placeNsrLon",
        "placeNsrLat",
        "exitType",
        "exitDate",
        "exitPlace",
        "exitLon",
        "exitLat",
        "course",
        "speed",
        "fuelLight",
        "fuelHeavy",
        "fuelSpg",
        "water",
        "incidents",
        "shipFault",
        "emergency",
        "atmTemperature" ,
        "atmPressure" ,
        "windDir" ,
        "windSpeed" ,
        "visibility" ,
        "weatherEvents",
        "waterTemperature" ,
        "iceCompression" ,
        "iceRidge" ,
        "iceDestruction" ,
        "icing",
        "iceEvents",
        "equipmentFault",
        "shipId" ,
        "ct",
        "ca",
        "cb",
        "cc",
        "sa" ,
        "sb" ,
        "sc"
    ]
  },
  nameMarker : ""
};

export { state as default };
